widgets:
    -
        position: left
        type: profile
        # Author name
        author: 张三
        # Author title
        author_title: 这是一个关于C4D和Blender的故事
        # Author's current location
        location: 
        # URL or path to the avatar image
        avatar: 
        # Whether show the rounded avatar image
        avatar_rounded: false
        # Email address for the Gravatar
        gravatar: 
        # URL or path for the follow button
        follow_link: https://github.com/ppoffice
        # Links to be shown on the bottom of the profile widget
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/ppoffice
            Facebook:
                icon: fab fa-facebook
                url: https://facebook.com
            Twitter:
                icon: fab fa-twitter
                url: https://twitter.com
            Dribbble:
                icon: fab fa-dribbble
                url: https://dribbble.com
            RSS:
                icon: fas fa-rss
                url: /    
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: toc
        toc: true
        # Whether to show the index of each heading
        index: true
        # Whether to collapse sub-headings when they are out-of-view
        collapsed: true
        # Maximum level of headings to show (1-6)
        depth: 3
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: tags   
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: recent_posts
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: categories
